IndiceDiario ={
    "AZUAY" : [100,2.7] ,
    "BOLÍVAR-BOLIVAR" : [], 
    "CAÑAR" : [], 
    "AZOGUES" : [],
    "CARCHI" : [], 
    "CHIMBORAZO" : [], 
    "COTOPAXI" : [], 
    "EL ORO" : [], 
    "ESMERALDAS" : [], 
    "GALÁPAGOS" : [], 
    "GUAYAS" : [],
    "IMBABURA" : [],
    "LOJA" : [], 
    "LOS RÍOS - LOS RIOS" : [],
    "MANABÍ - MANABI" : [], 
    "MORONA SANTIAGO" : [],
    "NAPO" : [], 
    "ORELLANA" : [],
    "PASTAZA" : [], 
    "PICHINCHA" : [],
    "SANTA ELENA" : [],
    "SANTO DOMINGO DE LOS TSÁCHILAS - SANTO DOMINGO - SANTO DOMINGO DE LOS TSACHILAS" : [],
    "SUCUMBÍOS-SUCUMBIOS" : [], 
    "TUNGURAHUA" : [], 
    "ZAMORA CHINCHIPE" : []
}